### ISSUE TITLE
can't edit location of pins

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#230] opened 2018-08-03 15:59 UTC

**Comment by martincf** [comment] 2018-08-29 10:03
Duplicate of #282

**Closed as completed by martincf** 2018-08-29 10:03 UTC

**Comment by amytodd** [comment] 2018-08-29 12:36
Has this been resolved?

Thanks
Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________

**Comment by edtjones** [comment] 2018-08-29 12:40
@amytodd no, but this ticket is a dupe of #282
