### ISSUE TITLE
Creative Commons  on every record

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#455] opened 2018-10-10 08:48 UTC
HLF would like us to add the creative commons 'label' plus a link to what it means on the record form, meaning that everyone who looks at a record should be able to see it.

**Comment by andyError** [comment] 2018-10-11 10:51
Closing, dupe of: https://github.com/layersoflondon/application/issues/449

**Closed as completed by andyError** 2018-10-11 10:51 UTC
Labels: Content
