### ISSUE TITLE
Not showing all pins

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#346] opened 2018-08-31 15:50 UTC
If I search for Seager Bookshop what appears on the map, even when I zoom in is one record. (not always the same one). In the tray, it shows far more records. The map should show them all too.

**Comment by edtjones** [comment] 2018-08-31 18:38
Can I have screenshots? I can’t make this happen. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by selrashidi** [comment] 2018-09-03 10:34
The above is what I get when I search for Seager -Two pins:


https://beta.layersoflondon.org/map/records/707


https://beta.layersoflondon.org/map/records/764


However in the tray I can see more records:


[cid:79c5f88a-3fae-49d3-abc7-163c2a06c9a8]


Also, if I click on any of the records and try to go back, it takes me back before my search.


Let me know if you need further explanation.


Thanks


Seif



________________________________

**Comment by edtjones** [comment] 2018-09-04 14:35
Sorry @selrashidi  I don't see your screenshots. Can you attach directly to the github issue please?

**Comment by edtjones** [comment] 2018-09-07 00:49
Dupe of #353

**Closed as completed by edtjones** 2018-09-07 00:49 UTC
Labels: High priority
