### ISSUE TITLE
User feedback online

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#156] opened 2018-06-19 14:09 UTC
From Amy: Feedback from pin entries (first/ 20th/ 50th); how did you hear about the project/ was it easy to use/ how likely are you to add another pin - is this happening?

**Comment by Forester1** [comment] 2018-06-26 06:52
Will require input from independent evaluator

**Comment by andyError** [comment] 2018-10-11 16:17
Closing as near-enough dupe of: https://github.com/layersoflondon/application/issues/256

**Closed as completed by andyError** 2018-10-11 16:17 UTC
