### ISSUE TITLE
Description disappearing

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#670] opened 2020-09-23 10:04 UTC
Just to let you know as well that I was having problems with uploading the images which makes me wonder whether there might be some bugs in the system. It may just have been my internet connection (although existent and regular, rather slow), but I noticed both that when I clicked save, the image credit remained but that the description then disappeared, both when I saved images individually or as a group. Secondly, I also noticed that a couple of times when I saved the descriptions and credits for the images, those descriptions would all then be shifted along by one image so images and descriptions were then all out of kilter. I'm still having real problems with all the images for the Half Moon Hotel on Borough High Street. Either descriptions are being lost or shifted around, so I'm going to have a break from it to see if the Layers system just needs to catch up on itself (and to give myself a break as it's quite infuriating!).

**Comment by EliWei** [comment] 2020-09-29 09:44
Another user (Elisabeth's got the Tweet and Twitter handle), has experienced similar things.

**Comment by edtjones** [comment] 2020-10-09 10:40
Can't repeat; will be a combination of user / data / browser which is doing this.

**Comment by mpdavies** [comment] 2020-11-20 15:27
Seems unclear what the issue is

**Comment by edtjones** [comment] 2020-11-25 14:42
I think we should close this but leave the labels so we can sanity-check and reach out to the affected user.

**Closed as completed by edtjones** 2020-11-25 14:42 UTC
Labels: Pre-migration Review, effort-large
