### ISSUE TITLE
Map: layer tool panel – reorder layers

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#193] opened 2018-07-20 09:01 UTC
> Layer tools box: Need to be able to reorder the layers here? At the moment you have to go back to the Layers selection page, click off and on again (and see earlier comment about not knowing which ones are on or off). Could you grab a layer and move it down the list to change the order?

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by Forester1** [comment] 2018-08-09 16:08
Feedback on beta:
Layer tools box: The grab function to change opacity needs adjusting a bit – it only works if you 'grab' it in the right way, ie with the hand squarely on top – could be a bit less precise

After selecting layers and viewing the map, if wanting to select new layers with Choose new layers, the website is crashing each time

Would be good to be able to de-select layers from the Tools box

**Comment by andyError** [comment] 2018-10-10 13:02
Closing as dupe of: https://github.com/layersoflondon/application/issues/299

**Closed as completed by andyError** 2018-10-10 13:02 UTC
