### ISSUE TITLE
Adding a record doesn't allow you to zoom into map to choose a location accurately

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#209] opened 2018-07-25 09:06 UTC
When I come to add a new record, it takes me to a zoomed out map, and yet I can't zoom in to add a pin, I have to choose a location based on the zoomed out view

**Comment by Forester1** [comment] 2018-07-26 13:18
Please amend so that Zoom in/Zoom out buttons work when adding a new record. 
![image](https://user-images.githubusercontent.com/6515338/43264683-ae891964-90de-11e8-9faf-20934ba7e92b.png) @edtjones

**Comment by martincf** [comment] 2018-07-31 10:29
have you tried the + & - buttons on the map? On my Mac, I usually zoom in with the trackpad or mouse too. which machine and browser are you using?

**Comment by selrashidi** [comment] 2018-07-31 10:42
I tried. It does not work: you have to zoom to the place you want and then click add record, you can't choose add record and then zoom in on the map.


I am using Google Chrome and my machine is a Dell Optiplex 7020.


Best regards,


Seif




________________________________

**Comment by edtjones** [comment] 2018-07-31 10:44
We pushed a change to this on Friday - the issue is that the 'click on the map' message container is/was overlaying the buttons. If it's not working we'll need to do another fix.

**Comment by Forester1** [comment] 2018-08-02 15:49
@edtjones I don't believe it is working. I can zoom in with a mouse wheel but this may not be obvious to most.

**Comment by edtjones** [comment] 2018-08-02 16:17
We will have another look @Forester1

**Comment by andyError** [comment] 2018-08-03 11:40
Fixed now.

**Closed as completed by andyError** 2018-08-03 11:40 UTC
Labels: High priority
