### ISSUE TITLE
I set up a record for Charlton House recently – there seems to be a strange quirk in the date cell. When I add the date of completion, 1612, the date then changes to other years, e.g. 1610 or 11.  Frustratingly inaccurate dates!

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#409] opened 2018-09-27 15:24 UTC
from user

**Comment by andyError** [comment] 2018-10-09 15:41
The developers are aware of this, I think there's a couple of tickets pertaining to this bug, so I will bring them all together.

**Comment by andyError** [comment] 2018-10-09 15:44
Closing as dupe of: https://github.com/layersoflondon/application/issues/443

**Closed as completed by andyError** 2018-10-09 15:44 UTC
