### ISSUE TITLE
Design & UX: add example placeholder content in Add Record forms

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#130] opened 2018-06-15 10:47 UTC
From Hendrik:

> **Title:** Can we add in an example title? For example "Trebor sweet factory on Smith Street"

> **Description:** Can we add in an example Description or example descriptions instructions? - Can we insert a basic character limit here (say 10-25 characters) to encourage users to add some more detailed content

**Comment by andyError** [comment] 2018-10-11 16:48
Closing as dupe of: https://github.com/layersoflondon/application/issues/310

**Closed as completed by andyError** 2018-10-11 16:48 UTC
