### ISSUE TITLE
Feedback on beta: Edit Record

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#254] opened 2018-08-09 16:23 UTC
Example process
Used drag and drop: Working. Dragged 3 images over. Set as primary image working. Entered image details for images 1-3. Clicked Save record. 
The end result is 8 Images were uploaded (several duplicates). This was not visible in the record when editing.
Delete image: Can clearly see 8 images but no way of deleting them?
Go to _account details > Records & Collection_s
Can see the draft records I have added but no way to delete individual records, duplicates or incorrect records, through the account interface or through editing the record itself. See image below: 

![image](https://user-images.githubusercontent.com/6515338/43911981-d5145f24-9bf8-11e8-9401-e8aa750f5716.png)

**Comment by andyError** [comment] 2018-08-30 11:17
I'm closing this. The later part (deleting records) is fixed, and the former part (deleting images) is a duplicate of another ticket.

**Closed as completed by andyError** 2018-08-30 11:17 UTC
Labels: High priority
