### ISSUE TITLE
Opacity slider

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#92] opened 2017-01-03 11:31 UTC
A small point, but any chance the opacity sliders could work dynamically while the slide bars are moved, rather than after a level has been chosen?

**Comment by edtjones** [comment] 2017-01-03 11:39
Might be possible @mpdavies but I suspect @foxpaul did it to avoid nasty flickering as it redraws the screen. Will investigate. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment] 2017-01-04 20:18
Have fixed in development commit #fb62b965

**Closed by edtjones** 2017-01-04 20:18 UTC

**Comment by andyError** [comment] 2018-10-12 10:26
Closing, dupe of: https://github.com/layersoflondon/application/issues/437
