### ISSUE TITLE
When creating teams, you can create duplicates - if it could provide suggestions based on similar names, it will reduce the number of dupes and increase visibility of existing teams / collections. 

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#418] opened 2018-09-28 15:09 UTC
Suggesting similar to, can also work for reducing duplications of records (will be helpful in a few years time)

**Comment by andyError** [comment] 2018-10-11 12:09
Closing, dupe of: https://github.com/layersoflondon/application/issues/427

**Closed as completed by andyError** 2018-10-11 12:09 UTC
